# Lista de artistas para coleta de músicas modernas (2023+)
# Gerada automaticamente

ARTISTAS_MODERNOS = [
    "Henrique & Juliano",
    "Jorge & Mateus",
    "Matheus & Kauan",
    "Zé Neto & Cristiano",
    "Hugo & Guilherme",
    "Guilherme & Benuto",
    "Marcos & Belutti",
    "Israel & Rodolffo",
    "João Bosco & Vinícius",
    "Clayton e Romário",
    "Pedro Henrique & Fernando",
    "George Henrique & Rodrigo",
    "Antony & Gabriel",
    "Ryan e Ruan",
    "Fred e Gustavo",
    "Brenno & Matheus",
    "Gusttavo Lima",
    "Luan Santana",
    "Gustavo Mioto",
    "Murilo Huff",
    "Felipe Araújo",
    "Eduardo Costa",
    "Zé Felipe",
    "Luan Pereira",
    "Wesley Safadão",
    "Gabriel Diniz",
    "Jonas Esticado",
    "Thiago Freitas",
    "João Gomes",
    "Tarcísio do Acordeon",
    "Zé Vaqueiro",
    "Eric Land",
    "Marília Mendonça",
    "Maiara & Maraisa",
    "Simone Mendes",
    "Ana Castela",
    "Lauana Prado",
    "Paula Fernandes",
    "Mari Fernandez",
    "Naiara Azevedo",
    "Roberta Miranda",
    "Elba Ramalho",
    "Fabiana Cantilo",
    "Gabi Martins",
    "Yasmin Santos",
    "Racyne e Rafael",
    "Duda Beat",
    "Luísa Sonza",
    "João Gustavo e Murilo",
    "Rafa & Pipo Marques",
    "Diego e Victor Hugo",
    "Fiduma & Jeca",
    "Conrado & Aleksandro",
    "Léo & Raphael",
    "Ícaro e Gilmar",
    "Lucas & Higor",
    "Bruno & Denner",
    "Zé Ricardo & Thiago",
    "Kleo Dibah",
    "Rayane & Rafaela",
    "Israel Novaes",
    "Anitta",
    "Ludmilla",
    "IZA",
    "MC Hariel",
    "MC Daniel",
    "MC Ryan SP",
    "Kevin o Chris",
    "Dennis DJ",
    "Pabllo Vittar",
    "Gloria Groove",
    "Vitão",
    "Ferrugem",
    "Thiaguinho",
    "Péricles",
    "Leonardo",
    "Daniel",
    "Sérgio Reis",
    "Chitãozinho e Xororó",
    "Bruno e Marrone",
    "Zezé Di Camargo & Luciano",
    "Leandro & Leonardo",
    "Victor & Leo",
    "Edson & Hudson",
    "Rick & Renner",
]

# Total: 85 artistas
